package com.compname.lob.domain.workorder;

import java.util.List;
import java.util.Map;

import com.google.common.collect.Maps;

/**
 * EligibilityWorkOrder
 * 
 * @author vegirl1
 * @since Jun 15, 2015
 * @version $Revision$
 */
public class EligibilityWorkOrder extends AbstractWorkOrder {

    private static final long               serialVersionUID = 2229963377886003635L;

    public static final String              RECORD_TYPE_ELIG = "ELIG";

    private String                          VLOADFormat;
    private String                          GipsyFormat;
    private String                          SAGFormat;

    private String                          dataIntegrityReport;
    private String                          activeClassAndDivExcpRprtRunDate;
    private String                          pharmacareRptRunDate;
    private String                          waiverOfPremiumRunDate;
    private String                          gipsyEmailReportRunDate;
    private String                          pharmaCareEnrollDate;

    private String                          futureTransactionReportRunDate;
    private String                          certifcateMappingReportRunDate;

    // Map<MANU_CORE, List{[12345,001,A],[12345,002,B],etc.}>
    private Map<String, List<List<String>>> planMaps         = Maps.newLinkedHashMap();

    private String                          certConversionRequired;
    private String                          certAutoGenerated;
    private String                          startingCertNumber;

    private Map<String, List<List<String>>> certificateMaps  = Maps.newLinkedHashMap();

    private Map<String, List<List<String>>> benefitMaps      = Maps.newLinkedHashMap();

    private Map<String, List<List<String>>> deductibleMaps   = Maps.newLinkedHashMap();

    // others WorkOrders that come along with Eligibility one
    private ClaimsWorkOrder                 claimsWorkOrder;

    private DrugClaimsWorkOrder             drugClaimsWorkOrder;

    /**
     * Class constructor.
     * 
     */
    public EligibilityWorkOrder() {
        super(RECORD_TYPE_ELIG);
    }

    /**
     * Getter method of the <code>"vLOADFormat"</code> class attribute.
     * 
     * @return the vLOADFormat.
     */
    public String getVLOADFormat() {
        return this.VLOADFormat;
    }

    /**
     * Setter method of the <code>"vLOADFormat"</code> class attribute.
     * 
     * @param VLOADFormat the vLOADFormat to set.
     */
    public void setVLOADFormat(String VLOADFormat) {
        this.VLOADFormat = VLOADFormat;
    }

    /**
     * Getter method of the <code>"gipsyFormat"</code> class attribute.
     * 
     * @return the gipsyFormat.
     */
    public String getGipsyFormat() {
        return this.GipsyFormat;
    }

    /**
     * Setter method of the <code>"gipsyFormat"</code> class attribute.
     * 
     * @param GipsyFormat the gipsyFormat to set.
     */
    public void setGipsyFormat(String gipsyFormat) {
        this.GipsyFormat = gipsyFormat;
    }

    /**
     * Getter method of the <code>"sAGFormat"</code> class attribute.
     * 
     * @return the sAGFormat.
     */
    public String getSAGFormat() {
        return this.SAGFormat;
    }

    /**
     * Setter method of the <code>"sAGFormat"</code> class attribute.
     * 
     * @param SAGFormat the sAGFormat to set.
     */
    public void setSAGFormat(String SAGFormat) {
        this.SAGFormat = SAGFormat;
    }

    /**
     * Getter method of the <code>"dataIntegrityReport"</code> class attribute.
     * 
     * @return the dataIntegrityReport.
     */
    public String getDataIntegrityReport() {
        return this.dataIntegrityReport;
    }

    /**
     * Setter method of the <code>"dataIntegrityReport"</code> class attribute.
     * 
     * @param DataIntegrityReport the dataIntegrityReport to set.
     */
    public void setDataIntegrityReport(String dataIntegrityReport) {
        this.dataIntegrityReport = dataIntegrityReport;
    }

    /**
     * Getter method of the <code>"activeClassAndDivExcpRprtRunDate"</code> class attribute.
     * 
     * @return the activeClassAndDivExcpRprtRunDate.
     */
    public String getActiveClassAndDivExcpRprtRunDate() {
        return this.activeClassAndDivExcpRprtRunDate;
    }

    /**
     * Setter method of the <code>"activeClassAndDivExcpRprtRunDate"</code> class attribute.
     * 
     * @param ctiveClassAndDivExcpRprtRunDate the activeClassAndDivExcpRprtRunDate to set.
     */
    public void setActiveClassAndDivExcpRprtRunDate(String vctiveClassAndDivExcpRprtRunDate) {
        this.activeClassAndDivExcpRprtRunDate = vctiveClassAndDivExcpRprtRunDate;
    }

    /**
     * Getter method of the <code>"waiverOfPremiumRunDate"</code> class attribute.
     * 
     * @return the waiverOfPremiumRunDate.
     */
    public String getWaiverOfPremiumRunDate() {
        return this.waiverOfPremiumRunDate;
    }

    /**
     * Setter method of the <code>"waiverOfPremiumRunDate"</code> class attribute.
     * 
     * @param waiverOfPremiumRunDate the waiverOfPremiumRunDate to set.
     */
    public void setWaiverOfPremiumRunDate(String waiverOfPremiumRunDate) {
        this.waiverOfPremiumRunDate = waiverOfPremiumRunDate;
    }

    /**
     * Getter method of the <code>"gipsyEmailReportRunDate"</code> class attribute.
     * 
     * @return the gipsyEmailReportRunDate.
     */
    public String getGipsyEmailReportRunDate() {
        return this.gipsyEmailReportRunDate;
    }

    /**
     * Setter method of the <code>"gipsyEmailReportRunDate"</code> class attribute.
     * 
     * @param gipsyEmailReportRunDate the gipsyEmailReportRunDate to set.
     */
    public void setGipsyEmailReportRunDate(String gipsyEmailReportRunDate) {
        this.gipsyEmailReportRunDate = gipsyEmailReportRunDate;
    }

    /**
     * Getter method of the <code>"futureTransactionReportRunDate"</code> class attribute.
     * 
     * @return the futureTransactionReportRunDate.
     */
    public String getFutureTransactionReportRunDate() {
        return this.futureTransactionReportRunDate;
    }

    /**
     * Setter method of the <code>"futureTransactionReportRunDate"</code> class attribute.
     * 
     * @param FutureTransactionReportRunDate the futureTransactionReportRunDate to set.
     */
    public void setFutureTransactionReportRunDate(String futureTransactionReportRunDate) {
        this.futureTransactionReportRunDate = futureTransactionReportRunDate;
    }

    /**
     * Getter method of the <code>"certifcateMappingReportRunDate"</code> class attribute.
     * 
     * @return the certifcateMappingReportRunDate.
     */
    public String getCertifcateMappingReportRunDate() {
        return this.certifcateMappingReportRunDate;
    }

    /**
     * Setter method of the <code>"certifcateMappingReportRunDate"</code> class attribute.
     * 
     * @param CertifcateMappingReportRunDate the certifcateMappingReportRunDate to set.
     */
    public void setCertifcateMappingReportRunDate(String certifcateMappingReportRunDate) {
        this.certifcateMappingReportRunDate = certifcateMappingReportRunDate;
    }

    /**
     * Getter method of the <code>"certConversionRequired"</code> class attribute.
     * 
     * @return the certConversionRequired.
     */
    public String getCertConversionRequired() {
        return this.certConversionRequired;
    }

    /**
     * Setter method of the <code>"certConversionRequired"</code> class attribute.
     * 
     * @param CertConversionRequired the certConversionRequired to set.
     */
    public void setCertConversionRequired(String certConversionRequired) {
        this.certConversionRequired = certConversionRequired;
    }

    /**
     * Getter method of the <code>"certAutoGenerated"</code> class attribute.
     * 
     * @return the certAutoGenerated.
     */
    public String getCertAutoGenerated() {
        return this.certAutoGenerated;
    }

    /**
     * Setter method of the <code>"certAutoGenerated"</code> class attribute.
     * 
     * @param CertAutoGenerated the certAutoGenerated to set.
     */
    public void setCertAutoGenerated(String certAutoGenerated) {
        this.certAutoGenerated = certAutoGenerated;
    }

    /**
     * Getter method of the <code>"startingCertNumber"</code> class attribute.
     * 
     * @return the startingCertNumber.
     */
    public String getStartingCertNumber() {
        return this.startingCertNumber;
    }

    /**
     * Setter method of the <code>"startingCertNumber"</code> class attribute.
     * 
     * @param StartingCertNumber the startingCertNumber to set.
     */
    public void setStartingCertNumber(String startingCertNumber) {
        this.startingCertNumber = startingCertNumber;
    }

    /**
     * Getter method of the <code>"pharmaCareEnrollDate"</code> class attribute.
     * 
     * @return the pharmaCareEnrollDate.
     */
    public String getPharmaCareEnrollDate() {
        return this.pharmaCareEnrollDate;
    }

    /**
     * Setter method of the <code>"pharmaCareEnrollDate"</code> class attribute.
     * 
     * @param PharmaCareEnrollDate the pharmaCareEnrollDate to set.
     */
    public void setPharmaCareEnrollDate(String pharmaCareEnrollDate) {
        this.pharmaCareEnrollDate = pharmaCareEnrollDate;
    }

    /**
     * Getter method of the <code>"planMaps"</code> class attribute.
     * 
     * @return the planMaps.
     */
    public Map<String, List<List<String>>> getPlanMaps() {
        return this.planMaps;
    }

    /**
     * Setter method of the <code>"planMaps"</code> class attribute.
     * 
     * @param PlanMaps the planMaps to set.
     */
    public void setPlanMaps(Map<String, List<List<String>>> planMaps) {
        this.planMaps = planMaps;
    }

    /**
     * Getter method of the <code>"certificateMaps"</code> class attribute.
     * 
     * @return the certificateMaps.
     */
    public Map<String, List<List<String>>> getCertificateMaps() {
        return this.certificateMaps;
    }

    /**
     * Setter method of the <code>"certificateMaps"</code> class attribute.
     * 
     * @param CertificateMaps the certificateMaps to set.
     */
    public void setCertificateMaps(Map<String, List<List<String>>> certificateMaps) {
        this.certificateMaps = certificateMaps;
    }

    /**
     * Getter method of the <code>"benefitMaps"</code> class attribute.
     * 
     * @return the benefitMaps.
     */
    public Map<String, List<List<String>>> getBenefitMaps() {
        return this.benefitMaps;
    }

    /**
     * Setter method of the <code>"benefitMaps"</code> class attribute.
     * 
     * @param BenefitMaps the benefitMaps to set.
     */
    public void setBenefitMaps(Map<String, List<List<String>>> benefitMaps) {
        this.benefitMaps = benefitMaps;
    }

    /**
     * Getter method of the <code>"pharmacareRptRunDate"</code> class attribute.
     * 
     * @return the pharmacareRptRunDate.
     */
    public String getPharmacareRptRunDate() {
        return this.pharmacareRptRunDate;
    }

    /**
     * Setter method of the <code>"pharmacareRptRunDate"</code> class attribute.
     * 
     * @param PharmacareRptRunDate the pharmacareRptRunDate to set.
     */
    public void setPharmacareRptRunDate(String pharmacareRptRunDate) {
        this.pharmacareRptRunDate = pharmacareRptRunDate;
    }

    /**
     * Getter method of the <code>"claimsWorkOrder"</code> class attribute.
     * 
     * @return the claimsWorkOrder.
     */
    public ClaimsWorkOrder getClaimsWorkOrder() {
        return this.claimsWorkOrder;
    }

    /**
     * Setter method of the <code>"claimsWorkOrder"</code> class attribute.
     * 
     * @param claimsWorkOrder the claimsWorkOrder to set.
     */
    public void setClaimsWorkOrder(ClaimsWorkOrder claimsWorkOrder) {
        this.claimsWorkOrder = claimsWorkOrder;
    }

    /**
     * Getter method of the <code>"drugClaimsWorkOrder"</code> class attribute.
     * 
     * @return the drugClaimsWorkOrder.
     */
    public DrugClaimsWorkOrder getDrugClaimsWorkOrder() {
        return drugClaimsWorkOrder;
    }

    /**
     * Setter method of the <code>"drugClaimsWorkOrder"</code> class attribute.
     * 
     * @param DrugClaimsWorkOrder the drugClaimsWorkOrder to set.
     */
    public void setDrugClaimsWorkOrder(DrugClaimsWorkOrder drugClaimsWorkOrder) {
        this.drugClaimsWorkOrder = drugClaimsWorkOrder;
    }

    /**
     * Getter method of the <code>"deductibleMaps"</code> class attribute.
     * 
     * @return the deductibleMaps.
     */
    public Map<String, List<List<String>>> getDeductibleMaps() {
        return this.deductibleMaps;
    }

    /**
     * Setter method of the <code>"deductibleMaps"</code> class attribute.
     * 
     * @param aDeductibleMaps the deductibleMaps to set.
     */
    public void setDeductibleMaps(Map<String, List<List<String>>> aDeductibleMaps) {
        this.deductibleMaps = aDeductibleMaps;
    }
}
